name: dressagecompanionpackage
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #  intl: 0.17.0-nullsafety.2
  intl: 0.17.0

  # permission_handler: ^9.2.0
  permission_handler: ^10.0.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.3
  shared_preferences: ^2.0.15
  package_info_plus: ^5.0.1

  latlong2: ^0.9.0
#  flutter_compass: ^0.8.0
#  #  flutter_map: ^0.14.0
#  flutter_map: ^6.1.0
#  #  flutter_map:
#  flutter_map_location_marker: any
  # *** Google Ads ***
  #  google_mobile_ads: ^0.13.0
  google_mobile_ads: ^3.1.0

  http_parser:
  http: ^1.1.2
  uuid: ^4.2.1
  connectivity_plus: ^5.0.2

  gps_tracker:
    path: /Users/graeme/AndroidStudioProjects/gps_tracker
  gps_tracker_db:
    path: /Users/graeme/AndroidStudioProjects/gps_tracker_db

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
